"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os

APP = ['app.py']
DATA_FILES = [
    ('assets', [
        'assets/icon_idle.png',
        'assets/icon_recording.png',
        'assets/icon_processing.png',
        'assets/icon_error.png',
        'assets/app_icon.icns.icns'
    ]),
    ('assets/i18n', [
        'assets/i18n/en.yaml',
        'assets/i18n/ru.yaml',
    ]),
]

OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'LSUIElement': False,
        'CFBundleName': "Steno",
        'CFBundleDisplayName': "Steno",
        'CFBundleIdentifier': "com.sergeygalay.steno",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSMicrophoneUsageDescription': "Приложение записывает звук микрофона во время встреч.",
        'NSScreenCaptureUsageDescription': "Приложение записывает экран для сохранения видео встреч.",
    },
    'packages': ['rumps', 'certifi', 'objc', 'AVFoundation', 'Quartz', 'ApplicationServices', 'AppKit', 'Foundation'],
    'includes': ['google.genai'],
    'iconfile': 'assets/app_icon.icns.icns',
}

setup(
    app=APP,
    name="Steno",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
