"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
import sys

from setuptools import find_packages, setup

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(ROOT_DIR, "src")
if SRC_DIR not in sys.path:
    sys.path.insert(0, SRC_DIR)

APP = ['src/steno_app/app.py']
DATA_FILES = [
    ('assets', [
        'src/steno_app/assets/icon_idle.png',
        'src/steno_app/assets/icon_recording.png',
        'src/steno_app/assets/icon_processing.png',
        'src/steno_app/assets/icon_error.png',
        'src/steno_app/assets/app_icon.icns.icns'
    ]),
    ('assets/i18n', [
        'src/steno_app/assets/i18n/en.yaml',
        'src/steno_app/assets/i18n/ru.yaml',
    ]),
]

OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'LSUIElement': False,
        'CFBundleName': "Steno",
        'CFBundleDisplayName': "Steno",
        'CFBundleIdentifier': "com.sergeygalay.steno",
        'CFBundleVersion': "0.2.0",
        'CFBundleShortVersionString': "0.2.0",
        'NSMicrophoneUsageDescription': "Приложение записывает звук микрофона во время встреч.",
        'NSScreenCaptureUsageDescription': "Приложение записывает экран для сохранения видео встреч.",
    },
    'packages': ['rumps', 'certifi', 'objc', 'AVFoundation', 'Quartz', 'ScreenCaptureKit', 'ApplicationServices', 'AppKit', 'Foundation', 'steno_app', 'steno_app.ui', 'steno_app.services'],
    'includes': ['google.genai'],
    'iconfile': 'src/steno_app/assets/app_icon.icns.icns',
}

setup(
    app=APP,
    name="Steno",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    setup_requires=['py2app'],
)
